POST http://localhost:2222/videos
Content-Type: application/json
Accept-Language: pt-BR

{
    "title": "Video node",
    "description": "Video 1 description",
    "duration": 120
}

###
GET http://localhost:2222/videos?search=node

###
GET http://localhost:2222/videos

###
PUT http://localhost:2222/videos/3cc4fd4b-2001-4850-9c23-084f31455b9a
Content-Type: application/json
Accept-Language: pt-BR

{
    "title": "Video New Title",
    "description": " New Video description",
    "duration": 180
}

###
DELETE http://localhost:2222/videos/3cc4fd4b-2001-4850-9c23-084f31455b9a
