@onrender_url = https://api-node-postgresjs.onrender.com/
@localhost_url = http://localhost:2222

###
POST {{onrender_url}}videos
Content-Type: application/json
Accept-Language: pt-BR

{
    "title": "Video 44",
    "description": "Video 1 description",
    "duration": 120
}

###
GET {{onrender_url}}videos?search=node

###
GET {{onrender_url}}videos

###
PUT {{onrender_url}}videos/3cc4fd4b-2001-4850-9c23-084f31455b9a
Content-Type: application/json
Accept-Language: pt-BR

{
    "title": "Video New Title",
    "description": " New Video description",
    "duration": 180
}

###
DELETE {{onrender_url}}videos/3cc4fd4b-2001-4850-9c23-084f31455b9a
